services:
  server:
    container_name: zipzoong-server-dev
    build: 
      context: ./server
    env_file:
      - server/.env
    volumes:
      - .:/usr/src/app
    command: sh -c "python3 server/manage.py migrate --noinput &&
        python3 server/manage.py runserver 0:8000"
    expose:
      - "8000"
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
      
  db:
    container_name: zipzoong-db-dev
    image: mysql
    env_file:
      - server/.env
    ports:
      - 3307:3306
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    