services:
  server:
    container_name: zipzoong-server-prod
    build: 
      context: ./server
    env_file:
      - server/.env
    volumes:
      - .:/usr/src/app
    command: sh -c "python3 server/manage.py migrate --noinput &&
        python server/manage.py collectstatic --noinput &&
        gunicorn --bind 0:8000 server.config.wsgi:application"
    expose:
      - "8000"
    ports:
      - 8000:8000
    depends_on:
      - db
      
  db:
    container_name: zipzoong-db-prod
    image: mysql
    env_file:
      - server/.env
    ports:
      - 3308:3306
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul