services:
  server:
    build: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: sh -c "python3 manage.py makemigrations && 
            python3 manage.py migrate --noinput && 
            gunicorn --bind 0:8000 config.wsgi:application"
    expose:
      - "8000"
    ports:
      - 8000:8000
    depends_on:
      - db
      
  db:
    image: mysql
    env_file:
      - .env
    ports:
      - 3308:3306
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul