services:
  server:
    container_name: zipzoong-server
    build: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: sh -c "python3 manage.py makemigrations && 
            python3 manage.py migrate --noinput && 
            python3 manage.py runserver 0:8000"
    expose:
      - "8000"
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - db
      
  db:
    container_name: zipzoong-db
    image: mysql
    env_file:
      - .env
    ports:
      - 3307:3306
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./.mysql/:/var/lib/mysql/