# Generated by Django 4.0.5 on 2022-10-06 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('sido_addr', models.CharField(max_length=32)),
                ('gungu_addr', models.CharField(max_length=32)),
                ('street_addr', models.CharField(max_length=128)),
                ('detail_addr', models.CharField(max_length=256, null=True)),
                ('postal_code', models.CharField(max_length=6, null=True)),
                ('sale_price', models.PositiveIntegerField(null=True)),
                ('charter_rent', models.PositiveIntegerField(null=True)),
                ('monthly_rent', models.PositiveIntegerField(null=True)),
                ('monthly_deposit', models.PositiveIntegerField(null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성 날짜')),
                ('modified_dt', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
            ],
            options={
                'db_table': 'house',
            },
        ),
        migrations.CreateModel(
            name='HouseOptionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField()),
                ('value', models.CharField(max_length=50, unique=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
            ],
            options={
                'db_table': 'house_option_code',
            },
        ),
        migrations.CreateModel(
            name='HouseDetail',
            fields=[
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='houses.house')),
                ('type_option', models.CharField(max_length=20, null=True)),
                ('floor_option', models.CharField(max_length=10, null=True)),
                ('floor', models.SmallIntegerField(null=True)),
                ('rooms_option', models.CharField(max_length=20, null=True)),
                ('rooms', models.SmallIntegerField(null=True)),
                ('restroom_option', models.CharField(max_length=10, null=True)),
                ('rests', models.SmallIntegerField(null=True)),
                ('duplex_option', models.CharField(max_length=10, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('modified_dt', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
            ],
            options={
                'db_table': 'house_detail',
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256, null=True, verbose_name='사진 경로')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='사진명')),
                ('type', models.CharField(max_length=16, null=True, verbose_name='사진 확장자')),
                ('size', models.PositiveIntegerField(null=True, verbose_name='사진 사이즈')),
                ('width', models.PositiveSmallIntegerField(null=True, verbose_name='사진 가로 길이')),
                ('height', models.PositiveSmallIntegerField(null=True, verbose_name='사진 세로 길이')),
                ('wh_type', models.SmallIntegerField(null=True, verbose_name='사진 크기 타입')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houses.house')),
            ],
            options={
                'db_table': 'house_image',
            },
        ),
    ]
